repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-added-large-files
    -   id: end-of-file-fixer
    -   id: check-ast
- repo: https://github.com/bridgecrewio/checkov.git
  rev: '3.1.23'
  hooks:
    - id: checkov
      verbose: true
      args: [--download-external-modules, 'true']
